# -*- coding: utf-8 -*-
"""task.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HPoawXHFozswbypM2mX8Fhg_6wnOGFd1
"""

l1 = [2,4,6,8,10]
for i in l1 :
  print("square",i**2)
for i in l1:
  print("cube",i**3)

